name: GitVersion Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  GitVersion_action:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.1
      with:
        versionSpec: '6.0.x'
        includePrerelease: true

    - name: Output the FullSemVer variable
      uses: gittools/actions/gitversion/command@v3.1.1
      with:
        arguments: '/showvariable FullSemVer'

    - name: Output the formatted version
      uses: gittools/actions/gitversion/command@v3.1.1
      with:
        arguments: '/format {Major}.{Minor}' # any Output Variable can be used here